name: torch-etc
channels:
  - conda-forge
dependencies:
  - pytorch>=1.7.1
  # - python=3.6   # or 2.7
  # - bokeh=0.9.2
  # - numpy=1.9.*
  # - nodejs=0.10.*
  # - flask
  # - pip:
  #   - Flask-Testing