name: base
channels:
  - conda-forge
dependencies:
  - numpy>=1.9.*
  - numpydoc>=0.7.0
  - scipy>=0.19.*
  - pandas>=1.1.5
  - swig>=4.0.0
  - pytorch>=1.7.1
  - lightfm>=1.16
  - numba>=0.52.0
  - flake8
  - pytest
