name: torch-etc
channels:
  - conda-forge
dependencies:
  - numpy>=1.9.*
  - numpydoc>=0.7.0
  - scipy>=0.19.*
  - pandas>=1.1.5
  - swig>=4.0.0
  - pytorch>=1.7.1
  # - python=3.6   # or 2.7
  # - bokeh=0.9.2
  # - nodejs=0.10.*
  # - flask
  # - pip:
  #   - Flask-Testing